version: "3.8"

services:
    postgres:
        image: postgres:16
        container_name: autoflex-db
        environment:
            POSTGRES_DB: autoflexdb
            POSTGRES_USER: 
            POSTGRES_PASSWORD: 
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
